repository: sophshep/manager-resources

style: dark

sass:
  load_paths:
    - node_modules

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "sidebar"
      is_post: true

topics:
  - name: Consulting
    image_url: https://github.com/taoge64/taoge64.github.io/raw/design/img/consulting.png

  - name: Block Chain
    image_url: https://github.com/taoge64/taoge64.github.io/raw/design/img/blockchain.png

  - name: Sass
    github_name: sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png




