repository: sophshep/manager-resources

style: dark

sass:
  load_paths:
    - node_modules

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "sidebar"
      is_post: true

topics:
  - name: Consulting
    #github_name: sass
    image_url: https://github.com/taoge64/taoge64.github.io/raw/design/img/consulting.png
    
  - name: Business
    image_url: https://github.com/taoge64/taoge64.github.io/raw/design/img/business.png
            
  - name: Data Analytics
    image_url: https://github.com/taoge64/taoge64.github.io/raw/design/img/bigdata.png

  - name: Artificial Intelligence
    image_url: https://github.com/taoge64/taoge64.github.io/raw/design/img/ai.png

  - name: Big Data Application
    image_url: https://github.com/taoge64/taoge64.github.io/raw/design/img/blockchain.png
    
  - name: Block Chain
    image_url: https://github.com/taoge64/taoge64.github.io/raw/design/img/blockchain.png



